[package]
name = "timelapse"
version = "0.1.0"
authors = ["Daniel Werner <dan.werner@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
